lib/src/code_field/code_field.dart
#14 Add CodeField.lineNumbers from BertrandBev
=> lineNumbers for showing/hiding line numbers

lib/src/code_field/code_field.dart
=> Changed textStyle from late to final

lib/code_text_field.dart, lib/src/code/code.dart, lib/src/code/code_line.dart, lib/src/code/text_range.dart, lib/src/code/tokens.dart, lib/src/code_field/code_controller.dart, lib/src/code_field/code_field.dart, lib/src/code_field/text_editing_value.dart, pubspec.yaml, test/src/code/code_test.dart, test/src/code_field/code_controller_test.dart
=> Support read-only code by end-of-line comments (#22)

lib/src/code/code.dart, lib/src/code_field/code_controller.dart, test/src/code/code_test.dart, test/src/code_field/code_controller_test.dart
=> Language-specific comments when parsing EOL comment tokens

lib/src/named_sections/named_section.dart, lib/src/named_sections/parsers/abstract.dart, lib/src/named_sections/parsers/brackets_start_end.dart, lib/src/single_line_comments/single_line_comment.dart, pubspec.yaml, test/src/named_sections/parsers/brackets_start_end_test.dart
=> Add BracketsStartEndNamedSectionParser

lib/code_text_field.dart, lib/src/code/code.dart, lib/src/code/code_line.dart, lib/src/code_field/code_controller.dart, lib/src/named_sections/parsers/abstract.dart, lib/src/named_sections/parsers/brackets_start_end.dart, test/src/code/code_test.dart, test/src/named_sections/parsers/brackets_start_end_test.dart
=> Use named sections for read-only code

lib/flutter_code_editor.dart, lib/src/folding/foldable_block.dart, lib/src/folding/foldable_block_type.dart, lib/src/folding/invalid_foldable_block.dart, lib/src/folding/parsers/abstract.dart, lib/src/folding/parsers/highlight.dart, lib/src/folding/parsers/line_semantics.dart, lib/src/highlight/keyword_semantics.dart, lib/src/highlight/node.dart, lib/src/highlight/node_classes.dart, lib/src/highlight/result.dart, test/src/folding/parsers/highlight_parser_test.dart
=> Add HighlightFoldableBlockParser, add tests for Java

.gitignore, example/lib/custom_code_box.dart, lib/src/code_field/code_controller.dart, lib/src/symbols.dart, test/src/code_field/code_controller_tab_test.dart
=> Tab symbol is replaced with spaces on fullText set (#62)

lib/src/code/code.dart, lib/src/code/string.dart, lib/src/code_field/code_controller.dart, test/src/code/code_get_edit_result_test.dart, test/src/code/string_get_changed_range_around_selection_test.dart, test/src/code_field/code_controller_folding_test.dart, test/src/code_field/code_controller_readonly_test.dart
=> Disambiguate changed ranges by snapping to selection (#90)

lib/src/folding/parsers/python.dart, test/src/folding/parsers/python_parser_test.dart
=> issue108 fix python folding

lib/src/code_field/code_controller.dart, test/src/code_field/code_controller_readonly_sections_test.dart, test/src/common/snippets.dart
=> Change read-only section names (#110)

lib/src/code_field/code_controller.dart, lib/src/history/code_history_controller.dart, lib/src/history/limit_stack.dart, test/src/history/code_history_controller_test.dart
=> Do not delete redo history on selection change (#133)

lib/src/code/code.dart, lib/src/code_field/text_editing_value.dart, lib/src/folding/foldable_block.dart, test/src/code_field/code_controller_visible_sections_test.dart, test/src/code_field/text_editing_value_select_test.dart, test/src/code_field/text_editing_value_test.dart, test/src/common/text_editing_value.dart, test/src/folding/foldable_block_test.dart, test/src/folding/parsers/highlight_parser_go_test.dart, test/src/folding/parsers/highlight_parser_scala_test.dart
=> Fix FoldableBlock.joinIntersecting(), fix newline handling after a service comment, export TextEditingValue.typed, add TextEditingValue.select

test/src/code_field/code_controller_visible_sections_test.dart, test/src/code_field/tabs_to_spaces_test.dart, test/src/folding/parsers/highlight_parser_scala_test.dart, test/src/folding/parsers/python_parser_test.dart
=> Prints removed from string literals in tests

example/lib/03.change_language_theme/home_screen.dart, lib/src/code_field/span_builder.dart
- Resolves #151 
- Resolves #152
=> Make visible sections not pale

lib/src/code_modifiers/indent_code_modifier.dart, test/src/code_modifiers/indent_modifier_test.dart
=> Issue135 indent after colon

lib/src/code/code.dart, lib/src/code_field/code_controller.dart, lib/src/folding/foldable_block.dart, lib/src/folding/foldable_block_matcher.dart, lib/src/gutter/gutter.dart, test/src/code_field/code_controller_folding_editing_test.dart, test/src/common/create_app.dart, test/src/folding/foldable_block_test.dart
- Resolves #131
CC https://github.com/apache/beam/issues/25279
=> Foldable block matcher fix

example/lib/03.change_language_theme/analyzer_implementation/dart_analyzer.dart, example/lib/03.change_language_theme/home_screen.dart, example/lib/03.change_language_theme/widgets/dropdown_selector.dart, lib/flutter_code_editor.dart, lib/src/analyzer/api/models/analysis_result.dart, lib/src/analyzer/impl/default_analyzer.dart, lib/src/code_field/code_controller.dart, lib/src/gutter/gutter.dart, pubspec.yaml, test/src/code_field/code_controller_analyzer_test.dart
=> Analyzer setters added

lib/src/code_field/code_field.dart, lib/src/wip/autocomplete/popup_controller.dart
=> fix windowSize initialization error

lib/src/code_field/code_field.dart, lib/src/gutter/error.dart
=> Error popup changed to use theme colors

.github/workflows/dart.yaml, lib/src/code_field/code_controller.dart, lib/src/code_field/code_field.dart, lib/src/gutter/gutter.dart, lib/src/util/public_notifier.dart, test/src/code_field/code_controller_readonly_test.dart, test/src/code_field/code_controller_shortcut_test.dart, test/src/history/code_history_controller_test.dart
=> Issue 241: Dispose suggestions popup

lib/src/code_field/search_result_highlighted_builder.dart, lib/src/search/search_navigation_controller.dart, test/src/search/search_navigation_test.dart
- Resolves #242
issue 242 fixed bug: Search selection jumped when change search pattern that also fit to current selection
=> issue 242 fixed bug: Search selection jumped when change search pattern that also fit to current selection

CHANGELOG.md, pubspec.yaml
=> Bump version, v0.3.3

CHANGELOG.md
- 🧹 Chore
v0.3.4 changelog update
- 🙅 no, because they aren't needed
- 🙅 No documentation needed
=> v0.3.4 changelog update
